function [time] = fdm_align2_nii(working_folder, file_ref, file_other)
% GENERATED BY fdm.py
% Use spm12 to align a pair of .nii files in working_folder. 
% Returns the time required for the alignment

% save & go to working path
cd_bkp = pwd;
cd(working_folder)


files = [file_ref;file_other];
tic;
spm_realign(files);
aln_time = toc;

time = aln_time;

%  restore path
cd(cd_bkp)

end