function [time] = fdm_convert_dcm_to_nii(working_folder, file, output_folder)
% GENERATED BY fdm.py
% Use spm12 to convert a .dcm file in working_folder into a .nii file. 
% Returns the time required for the conversion

% save & go to working path
cd_bkp = pwd;
cd(working_folder)

% check  that file is a .dcm
%if file(end-3:end) ~= '.dcm'
%    disp('ERROR');
%end

tic;
% convert
hdr = spm_dicom_headers(file);
spm_dicom_convert(hdr, 'all', 'flat', 'nii', output_folder);
cvt_time = toc;

time = cvt_time;

%  restore path
cd(cd_bkp)

end